-- Run with a role allowed to create databases, schemas and warehouses.
CREATE DATABASE IF NOT EXISTS TREND_ZONE_CDP;
CREATE SCHEMA IF NOT EXISTS TREND_ZONE_CDP.RAW;
CREATE SCHEMA IF NOT EXISTS TREND_ZONE_CDP.ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS TREND_ZONE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE TREND_ZONE_WH;
USE DATABASE TREND_ZONE_CDP;
