USE DATABASE TREND_ZONE_CDP;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMERS (
  CUSTOMER_ID VARCHAR(50), FIRST_NAME VARCHAR(100), LAST_NAME VARCHAR(100), EMAIL VARCHAR(255),
  PHONE VARCHAR(30), LOYALTY_TIER VARCHAR(30), CUSTOMER_SINCE DATE, CREATED_AT TIMESTAMP_TZ, CUSTOMER_ORIGIN VARCHAR(50)
);

CREATE OR REPLACE TABLE STORES (
  STORE_ID VARCHAR(50), STORE_NAME VARCHAR(150), CITY VARCHAR(100), STATE VARCHAR(100), COUNTRY VARCHAR(100), CREATED_AT TIMESTAMP_TZ
);

CREATE OR REPLACE TABLE PRODUCTS (
  PRODUCT_ID VARCHAR(50), SKU VARCHAR(100), PRODUCT_NAME VARCHAR(255), CATEGORY VARCHAR(100), UNIT_PRICE NUMBER(12,2), CREATED_AT TIMESTAMP_TZ
);

CREATE OR REPLACE TABLE OFFLINE_ORDERS (
  TRANSACTION_ID VARCHAR(50), CUSTOMER_ID VARCHAR(50), STORE_ID VARCHAR(50), PURCHASE_TIMESTAMP TIMESTAMP_TZ,
  CURRENCY VARCHAR(3), SUBTOTAL NUMBER(12,2), DISCOUNT NUMBER(12,2), TAX NUMBER(12,2), REVENUE NUMBER(12,2),
  PAYMENT_METHOD VARCHAR(50), CHANNEL VARCHAR(30), CREATED_AT TIMESTAMP_TZ
);

CREATE OR REPLACE TABLE OFFLINE_ORDER_ITEMS (
  LINE_ITEM_ID VARCHAR(50), TRANSACTION_ID VARCHAR(50), PRODUCT_ID VARCHAR(50), SKU VARCHAR(100),
  QUANTITY NUMBER(10,0), UNIT_PRICE NUMBER(12,2), LINE_TOTAL NUMBER(12,2), CREATED_AT TIMESTAMP_TZ
);
