-- Exact analytical view definitions exported with Snowflake GET_DDL.
USE DATABASE TREND_ZONE_CDP;
USE SCHEMA ANALYTICS;

create or replace view OFFLINE_GUEST_ORDERS(
	TRANSACTION_ID,
	PURCHASE_TIMESTAMP,
	STORE_ID,
	STORE_NAME,
	STORE_CITY,
	CURRENCY,
	REVENUE,
	PAYMENT_METHOD,
	CHANNEL,
	LINE_ITEM_COUNT
) as
SELECT
    O.TRANSACTION_ID,
    O.PURCHASE_TIMESTAMP,
    O.STORE_ID,
    S.STORE_NAME,
    S.CITY AS STORE_CITY,
    O.CURRENCY,
    O.REVENUE,
    O.PAYMENT_METHOD,
    O.CHANNEL,
    COUNT(I.LINE_ITEM_ID) AS LINE_ITEM_COUNT
FROM RAW.OFFLINE_ORDERS O
JOIN RAW.OFFLINE_ORDER_ITEMS I
    ON O.TRANSACTION_ID = I.TRANSACTION_ID
JOIN RAW.STORES S
    ON O.STORE_ID = S.STORE_ID
WHERE O.CUSTOMER_ID IS NULL
GROUP BY
    O.TRANSACTION_ID,
    O.PURCHASE_TIMESTAMP,
    O.STORE_ID,
    S.STORE_NAME,
    S.CITY,
    O.CURRENCY,
    O.REVENUE,
    O.PAYMENT_METHOD,
    O.CHANNEL;

create or replace view SEGMENT_CUSTOMER_TRAITS(
	USER_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE,
	LOYALTY_TIER,
	CUSTOMER_SINCE,
	CUSTOMER_ORIGIN,
	OFFLINE_ORDER_COUNT,
	OFFLINE_TOTAL_SPEND,
	OFFLINE_LAST_PURCHASE_AT
) as
SELECT
    C.CUSTOMER_ID AS USER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.EMAIL,
    C.PHONE,
    C.LOYALTY_TIER,
    C.CUSTOMER_SINCE,
    C.CUSTOMER_ORIGIN,

    COUNT(O.TRANSACTION_ID) AS OFFLINE_ORDER_COUNT,
    COALESCE(SUM(O.REVENUE), 0) AS OFFLINE_TOTAL_SPEND,
    MAX(O.PURCHASE_TIMESTAMP) AS OFFLINE_LAST_PURCHASE_AT

FROM RAW.CUSTOMERS C
LEFT JOIN RAW.OFFLINE_ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID

GROUP BY
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.EMAIL,
    C.PHONE,
    C.LOYALTY_TIER,
    C.CUSTOMER_SINCE,
    C.CUSTOMER_ORIGIN;

create or replace view SEGMENT_OFFLINE_ORDERS(
	MESSAGE_ID,
	TRANSACTION_ID,
	USER_ID,
	CUSTOMER_ORIGIN,
	EVENT_NAME,
	EVENT_TIMESTAMP,
	CURRENCY,
	SUBTOTAL,
	DISCOUNT,
	TAX,
	REVENUE,
	PAYMENT_METHOD,
	CHANNEL,
	STORE_ID,
	STORE_NAME,
	STORE_CITY,
	STORE_STATE,
	PRODUCTS
) as
SELECT
    O.TRANSACTION_ID AS MESSAGE_ID,
    O.TRANSACTION_ID,
    O.CUSTOMER_ID AS USER_ID,
    C.CUSTOMER_ORIGIN,
    'Offline Order Completed' AS EVENT_NAME,
    O.PURCHASE_TIMESTAMP AS EVENT_TIMESTAMP,
    O.CURRENCY,
    O.SUBTOTAL,
    O.DISCOUNT,
    O.TAX,
    O.REVENUE,
    O.PAYMENT_METHOD,
    O.CHANNEL,
    O.STORE_ID,
    S.STORE_NAME,
    S.CITY AS STORE_CITY,
    S.STATE AS STORE_STATE,

    ARRAY_AGG(
        OBJECT_CONSTRUCT(
            'product_id', I.PRODUCT_ID,
            'sku', I.SKU,
            'name', P.PRODUCT_NAME,
            'category', P.CATEGORY,
            'quantity', I.QUANTITY,
            'price', I.UNIT_PRICE,
            'line_total', I.LINE_TOTAL
        )
    ) WITHIN GROUP (ORDER BY I.LINE_ITEM_ID) AS PRODUCTS

FROM RAW.OFFLINE_ORDERS O

JOIN RAW.CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID

JOIN RAW.OFFLINE_ORDER_ITEMS I
    ON O.TRANSACTION_ID = I.TRANSACTION_ID

JOIN RAW.PRODUCTS P
    ON I.PRODUCT_ID = P.PRODUCT_ID

JOIN RAW.STORES S
    ON O.STORE_ID = S.STORE_ID

WHERE O.CUSTOMER_ID IS NOT NULL

GROUP BY
    O.TRANSACTION_ID,
    O.CUSTOMER_ID,
    C.CUSTOMER_ORIGIN,
    O.PURCHASE_TIMESTAMP,
    O.CURRENCY,
    O.SUBTOTAL,
    O.DISCOUNT,
    O.TAX,
    O.REVENUE,
    O.PAYMENT_METHOD,
    O.CHANNEL,
    O.STORE_ID,
    S.STORE_NAME,
    S.CITY,
    S.STATE;

