USE DATABASE TREND_ZONE_CDP;

-- Expected result: 0
SELECT COUNT(*) AS KNOWN_EVENTS_WITHOUT_USER_ID
FROM ANALYTICS.SEGMENT_OFFLINE_ORDERS
WHERE USER_ID IS NULL;

-- Expected result: 0
SELECT COUNT(*) AS DUPLICATE_MESSAGE_IDS
FROM (
  SELECT MESSAGE_ID FROM ANALYTICS.SEGMENT_OFFLINE_ORDERS
  GROUP BY MESSAGE_ID HAVING COUNT(*) > 1
);

-- Expected result: 0
SELECT COUNT(*) AS EMPTY_PRODUCT_ARRAYS
FROM ANALYTICS.SEGMENT_OFFLINE_ORDERS
WHERE PRODUCTS IS NULL OR ARRAY_SIZE(PRODUCTS) = 0;

-- Expected result: 0
SELECT COUNT(*) AS ORDER_TOTAL_MISMATCHES
FROM RAW.OFFLINE_ORDERS O
JOIN (
  SELECT TRANSACTION_ID, SUM(LINE_TOTAL) AS CALCULATED_SUBTOTAL
  FROM RAW.OFFLINE_ORDER_ITEMS GROUP BY TRANSACTION_ID
) I ON O.TRANSACTION_ID = I.TRANSACTION_ID
WHERE O.SUBTOTAL <> I.CALCULATED_SUBTOTAL
   OR O.REVENUE <> O.SUBTOTAL - O.DISCOUNT + O.TAX;

-- Expected result: 0
SELECT COUNT(*) AS GUEST_ORDERS_IN_SEGMENT_MODEL
FROM ANALYTICS.SEGMENT_OFFLINE_ORDERS
WHERE USER_ID IS NULL;

-- Expected result: 0
SELECT COUNT(*) AS INVALID_PHONE_FORMATS
FROM RAW.CUSTOMERS
WHERE LENGTH(REGEXP_REPLACE(PHONE, '[^0-9]', '')) <> 12;

-- Expected result: 0
SELECT COUNT(*) AS PLACEHOLDER_EMAIL_DOMAINS
FROM RAW.CUSTOMERS
WHERE EMAIL ILIKE '%@example.com';
