USE DATABASE TREND_ZONE_CDP;

SELECT CUSTOMER_ORIGIN, COUNT(*) AS CUSTOMER_COUNT
FROM RAW.CUSTOMERS GROUP BY CUSTOMER_ORIGIN ORDER BY CUSTOMER_ORIGIN;

SELECT CATEGORY, COUNT(*) AS PRODUCT_COUNT, MIN(UNIT_PRICE) AS LOWEST_PRICE, MAX(UNIT_PRICE) AS HIGHEST_PRICE
FROM RAW.PRODUCTS GROUP BY CATEGORY ORDER BY CATEGORY;

SELECT
  CASE WHEN O.CUSTOMER_ID IS NULL THEN 'GUEST_UNIDENTIFIED' ELSE C.CUSTOMER_ORIGIN END AS ORDER_TYPE,
  COUNT(*) AS ORDER_COUNT, SUM(O.REVENUE) AS TOTAL_REVENUE
FROM RAW.OFFLINE_ORDERS O
LEFT JOIN RAW.CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY 1 ORDER BY 1;

SELECT 'SEGMENT_OFFLINE_ORDERS' AS VIEW_NAME, COUNT(*) AS ROW_COUNT FROM ANALYTICS.SEGMENT_OFFLINE_ORDERS
UNION ALL SELECT 'OFFLINE_GUEST_ORDERS', COUNT(*) FROM ANALYTICS.OFFLINE_GUEST_ORDERS
UNION ALL SELECT 'SEGMENT_CUSTOMER_TRAITS', COUNT(*) FROM ANALYTICS.SEGMENT_CUSTOMER_TRAITS;
