-- Trend Zone: least-privilege Snowflake access for Segment Reverse ETL
-- Run with ACCOUNTADMIN or appropriately delegated security roles.
-- Never store an RSA private key, private-key passphrase, or Segment Write Key here.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TZ_SEGMENT_REVERSE_ETL_ROLE;

GRANT USAGE ON WAREHOUSE TREND_ZONE_WH
TO ROLE TZ_SEGMENT_REVERSE_ETL_ROLE;

GRANT USAGE ON DATABASE TREND_ZONE_CDP
TO ROLE TZ_SEGMENT_REVERSE_ETL_ROLE;

GRANT USAGE ON SCHEMA TREND_ZONE_CDP.ANALYTICS
TO ROLE TZ_SEGMENT_REVERSE_ETL_ROLE;

GRANT SELECT ON VIEW TREND_ZONE_CDP.ANALYTICS.SEGMENT_CUSTOMER_TRAITS
TO ROLE TZ_SEGMENT_REVERSE_ETL_ROLE;

GRANT SELECT ON VIEW TREND_ZONE_CDP.ANALYTICS.SEGMENT_OFFLINE_ORDERS
TO ROLE TZ_SEGMENT_REVERSE_ETL_ROLE;

CREATE USER IF NOT EXISTS TZ_SEGMENT_REVERSE_ETL_USER
    TYPE = SERVICE
    DEFAULT_ROLE = TZ_SEGMENT_REVERSE_ETL_ROLE
    DEFAULT_WAREHOUSE = TREND_ZONE_WH
    COMMENT = 'Dedicated service user for Trend Zone Segment Reverse ETL';

GRANT ROLE TZ_SEGMENT_REVERSE_ETL_ROLE
TO USER TZ_SEGMENT_REVERSE_ETL_USER;

-- Paste only the body of the generated public key when executing this statement.
-- Do not commit an environment-specific public key to the repository.
-- ALTER USER TZ_SEGMENT_REVERSE_ETL_USER
-- SET RSA_PUBLIC_KEY = '<PUBLIC_KEY_BODY>';

CREATE SCHEMA IF NOT EXISTS TREND_ZONE_CDP.__SEGMENT_REVERSE_ETL
    COMMENT = 'Segment-managed Reverse ETL state and checkpoint tables';

GRANT USAGE, CREATE TABLE
ON SCHEMA TREND_ZONE_CDP.__SEGMENT_REVERSE_ETL
TO ROLE TZ_SEGMENT_REVERSE_ETL_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA TREND_ZONE_CDP.__SEGMENT_REVERSE_ETL
TO ROLE TZ_SEGMENT_REVERSE_ETL_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA TREND_ZONE_CDP.__SEGMENT_REVERSE_ETL
TO ROLE TZ_SEGMENT_REVERSE_ETL_ROLE;

-- Verification
SHOW GRANTS TO USER TZ_SEGMENT_REVERSE_ETL_USER;
SHOW GRANTS TO ROLE TZ_SEGMENT_REVERSE_ETL_ROLE;
DESC USER TZ_SEGMENT_REVERSE_ETL_USER;

